const path=require('path'), fs=require('fs');
const { db, getSettings }=require('./db');
const { processPost }=require('./processor');
const { fetchGroupPosts }=require('./socialapis');
async function downloadImages(postId, urls){ const base=path.resolve(process.env.IMAGE_CACHE_DIR||'./data/images', postId); fs.mkdirSync(base,{recursive:true}); let i=0; for(const u of urls){try{const res=await fetch(u); if(!res.ok)continue; const p=path.join(base,`${i}.jpg`); fs.writeFileSync(p, Buffer.from(await res.arrayBuffer())); db.prepare('INSERT OR IGNORE INTO post_images(post_id,source_url,local_path,position) VALUES(?,?,?,?)').run(postId,u,p,i); i++;}catch{}}}
async function telegram(post, settings){ if(settings.telegram_enabled!=='true'||!process.env.TELEGRAM_BOT_TOKEN||!process.env.TELEGRAM_CHAT_ID)return; const msg=`🏠 New flat match\n${post.rent_text||''} ${post.matched_area||''}\n${post.source_post_url||''}\n\n${(post.message||'').slice(0,600)}`; await fetch(`https://api.telegram.org/bot${process.env.TELEGRAM_BOT_TOKEN}/sendMessage`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({chat_id:process.env.TELEGRAM_CHAT_ID,text:msg})}).catch(()=>{});}
function imageUrls(p){return [p.full_picture,p.picture,...(p.images||[]),...(p.attachments?.data||[]).map(a=>a.media?.image?.src)].filter(Boolean)}
async function ingest(){ const s=getSettings(); const group=s.group_url||process.env.FACEBOOK_GROUP_URL; if(!group) throw new Error('No Facebook group URL configured'); const posts=await fetchGroupPosts(group); let inserted=0, matched=0; for(const p of posts){ const id=String(p.id||p.post_id||p.url||p.permalink_url); if(!id)continue; const proc=processPost(p,s); const existed=db.prepare('SELECT id FROM posts WHERE id=?').get(id); db.prepare(`INSERT INTO posts(id,source_group_url,source_post_url,author_name,message,created_time,fetched_at,post_type,is_hall_sharing,rent_amount,rent_text,brokerage_label,matched_area,is_match,excluded_reason,raw_json) VALUES(@id,@source_group_url,@source_post_url,@author_name,@message,@created_time,@fetched_at,@post_type,@is_hall_sharing,@rent_amount,@rent_text,@brokerage_label,@matched_area,@is_match,@excluded_reason,@raw_json) ON CONFLICT(id) DO UPDATE SET message=excluded.message,post_type=excluded.post_type,is_hall_sharing=excluded.is_hall_sharing,rent_amount=excluded.rent_amount,rent_text=excluded.rent_text,brokerage_label=excluded.brokerage_label,matched_area=excluded.matched_area,is_match=excluded.is_match,excluded_reason=excluded.excluded_reason,raw_json=excluded.raw_json`).run({id,source_group_url:group,source_post_url:p.permalink_url||p.url||'',author_name:p.from?.name||p.author||'',created_time:p.created_time||p.timestamp||'',fetched_at:new Date().toISOString(),raw_json:JSON.stringify(p),...proc}); if(!existed){inserted++; await downloadImages(id.replace(/[^a-zA-Z0-9_-]/g,'_'), imageUrls(p)); if(proc.is_match){matched++; await telegram({id,source_post_url:p.permalink_url||p.url||'',...proc}, s);}} } return {inserted, matched, seen:posts.length};}
function recompute(){const s=getSettings(); const rows=db.prepare('SELECT id,raw_json FROM posts').all(); const upd=db.prepare('UPDATE posts SET message=@message,post_type=@post_type,is_hall_sharing=@is_hall_sharing,rent_amount=@rent_amount,rent_text=@rent_text,brokerage_label=@brokerage_label,matched_area=@matched_area,is_match=@is_match,excluded_reason=@excluded_reason WHERE id=@id'); rows.forEach(r=>upd.run({id:r.id,...processPost(JSON.parse(r.raw_json),s)})); return rows.length;}
module.exports={ingest,recompute};
