function list(s){return String(s||'').split(',').map(x=>x.trim()).filter(Boolean)}
function hasAny(text, words){const t=text.toLowerCase(); return words.some(w=>t.includes(w.toLowerCase()))}
function classify(text){const t=text.toLowerCase(); if(/\b(pg|paying guest)\b/.test(t))return'pg'; if(/\b(room|single occupancy|sharing)\b/.test(t))return'room'; if(/\b(1bhk|2bhk|3bhk|studio|flat|apartment)\b/.test(t))return'flat'; return'unknown'}
function hallSharing(text){return /\b(hall sharing|hall\s+available|living room|common hall)\b/i.test(text)}
function rent(text){const pats=[/(?:rent|price|₹|rs\.?|inr)\s*[:\-]?\s*(\d+(?:\.\d+)?)\s*(k|lakh|lac)?/i,/(\d+(?:\.\d+)?)\s*(k|lakh|lac)\s*(?:rent|pm|per month)?/i]; for(const p of pats){const m=text.match(p); if(m){let n=parseFloat(m[1]); if(m[2]){const u=m[2].toLowerCase(); n*=u==='k'?1000:100000} return {amount:Math.round(n), text:m[0]}}} return {amount:null,text:''}}
function brokerage(text){if(/\b(no brokerage|brokerage free|owner|direct owner)\b/i.test(text))return'no_brokerage'; if(/\b(broker|brokerage|agent)\b/i.test(text))return'brokerage'; return'unknown'}
function area(text, areas){const found=list(areas).find(a=>new RegExp(`\\b${a.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\b`,'i').test(text)); return found||''}
function processPost(post, settings){const text=[post.message,post.story,post.description].filter(Boolean).join('\n'); const excluded=hasAny(text,list(settings.exclude_keywords)); const kw=hasAny(text,list(settings.keywords)); const r=rent(text); const max=parseInt(settings.max_rent||'0',10); const ar=area(text,settings.areas); const maxOk=!max||!r.amount||r.amount<=max; const isMatch=!excluded && kw && maxOk && (!!ar || !settings.areas); return {message:text, post_type:classify(text), is_hall_sharing:hallSharing(text)?1:0, rent_amount:r.amount, rent_text:r.text, brokerage_label:brokerage(text), matched_area:ar, is_match:isMatch?1:0, excluded_reason: excluded?'Excluded keyword':(!kw?'No keyword':(!maxOk?'Above max rent':''))}}
module.exports={processPost};
